### ISSUE TITLE
0.8.0 Roadmap

### ISSUE THREAD

**Issue by sokomishalov** [sokomishalov/skraper#152]
- [ ] `getPosts` and extensions for it should return `Flow<Post>`and be paginable.
  - [x] make `getPosts` return `Flow<Post>` everywhere (https://github.com/sokomishalov/skraper/commit/8444e69d4d9181543358e986ae90fd98674d2306)
  - [x] Facebook pagination (https://github.com/sokomishalov/skraper/commit/8444e69d4d9181543358e986ae90fd98674d2306)
  - [x] 9Gag pagination (https://github.com/sokomishalov/skraper/commit/8444e69d4d9181543358e986ae90fd98674d2306)
  - [x] Reddit pagination (https://github.com/sokomishalov/skraper/commit/8444e69d4d9181543358e986ae90fd98674d2306)
  - [x] Telegram pagination (https://github.com/sokomishalov/skraper/commit/8444e69d4d9181543358e986ae90fd98674d2306)
  - [x] IFunny pagination (https://github.com/sokomishalov/skraper/commit/6fdf4ac0bca699d5cff3338b4b78beb5bbbc9e11) 
  - [x] Pikabu pagination (https://github.com/sokomishalov/skraper/commit/36547ffa3e9b9db2a8822762fa2ac4bc066b741c) 
  - [ ] pagination for other providers where it's possible
- [ ] add `author` and scrape it (where possible) (https://github.com/sokomishalov/skraper/pull/166)
- [x] add `statistics` field to `Post`, which includes `likes`, `reposts`, `views` and `comments` amount fields.
  - [x] `statistics` field added (https://github.com/sokomishalov/skraper/commit/6de11f1ade0e497b5ffe8162ba13bbe246e21b90)
  - [x] extract `reposts` per each provider where it's possible (https://github.com/sokomishalov/skraper/commit/8a2f4d0da527073922a6e495ec4ab8b2c14e3092)
- [x] add `statistics` field to `PageInfo`, which includes `posts`, `followers` and `following` amount fields.
  - [x] `statistics` field added (https://github.com/sokomishalov/skraper/commit/6de11f1ade0e497b5ffe8162ba13bbe246e21b90)
  - [x] extract `following` per each provider where it's possible (https://github.com/sokomishalov/skraper/commit/adee3fa37ac9501b3f66eae732d57cbb078fbf78)
 - [ ] provide interface replacement for uri/path
 - [x] remove `baseUrl` from `Skraper` interface (https://github.com/sokomishalov/skraper/commit/a31da1c84ad1d941dfb2acbe90bcd0201b7120fc)
 - [x] provide `UnknownMedia` type (https://github.com/sokomishalov/skraper/commit/a31da1c84ad1d941dfb2acbe90bcd0201b7120fc)

**Comment by sokomishalov** [comment]
Partially closed, still opened tasks are targeting to the next release.
