### ISSUE TITLE
0.9.0 Roadmap

### ISSUE THREAD

**Issue by sokomishalov** [sokomishalov/skraper#186]
- [ ] add `tags` field to the post
- [ ] add `author` and scrape it (where possible)
- [ ] provide interface replacement for uri/path
